#!/bin/sh
set -euo pipefail

set +x

IMAGE_NAME=${3:?missing image name}
DOCKER_REPO_ROOT=/opt/app-root/src

source_volume() {
    volume=$(docker volume create)
    container=$(docker create --user root --volume "${volume}:${DOCKER_REPO_ROOT}" "${IMAGE_NAME}" sh -c 'chgrp -fR root . && chmod -fR g+w .')
    docker cp "$PWD/local" "${container}:${DOCKER_REPO_ROOT}/perl5"
    docker cp "$PWD/lua_modules" "${container}:${DOCKER_REPO_ROOT}/"
    docker start "${container}" >/dev/null
    docker wait "${container}" >/dev/null
    docker logs ${container} >&2
    docker rm ${container} >/dev/null
    echo "$volume"
}

volume=$(source_volume)

remove_volume() {
	docker volume rm "${volume}"
}
trap remove_volume EXIT

s2i "$@" \
	--volume "${volume}:${DOCKER_REPO_ROOT}"
